package com.globalsolution.mentessolidarias.entities.enuns;

public enum Escolaridade {
    ENSINO_FUNDAMENTAL_INCOMPLETO,
    ENSINO_FUNDAMENTAL_COMPLETO,
    ENSINO_MEDIO_INCOMPLETO,
    ENSINO_MEDIO_COMPLETO,
    GRADUACAO_INCOMPLETA,
    GRADUACAO_COMPLETA,
    POS_GRADUACAO_INCOMPLETA,
    POS_GRADUACAO_COMPLETA;
}
