--Ancient Code
/*
*RM552292 ? Julia Nery
*RM98163 ? Júlia Figueiredo
*RM552389 ? Isabelli Heloiza
*RM550562 ? Larissa Akemi
*RM94679 ? Vínicius Becker
*/

--EXCLUSÃO DE TABELAS
DROP TABLE main_usuario CASCADE CONSTRAINTS;
DROP TABLE special_paciente CASCADE CONSTRAINTS;
DROP TABLE special_profissional CASCADE CONSTRAINTS;
DROP TABLE tb_prontuario CASCADE CONSTRAINTS;
DROP TABLE tb_avaliacao CASCADE CONSTRAINTS;
DROP TABLE tb_medicamento CASCADE CONSTRAINTS;
DROP TABLE tb_consulta CASCADE CONSTRAINTS;
DROP TABLE tb_receita CASCADE CONSTRAINTS;
DROP TABLE assoc_receita_medicamento CASCADE CONSTRAINTS;
DROP TABLE tb_tipo_usuario CASCADE CONSTRAINTS;
DROP TABLE tb_escolaridade CASCADE CONSTRAINTS;


--EXCLUSÃO DE SEQUENCIAS
DROP SEQUENCE AUTO_INCREMENT_PRONTUARIO;
DROP SEQUENCE AUTO_INCREMENT_MEDICAMENTO;
DROP SEQUENCE AUTO_INCREMENT_CONSULTA;
DROP SEQUENCE AUTO_INCREMENT_RECEITA;
DROP SEQUENCE AUTO_INCREMENT_RECEITA_MEDICAMENTO;
DROP SEQUENCE AUTO_INCREMENT_AVALIACAO;
DROP SEQUENCE AUTO_INCREMENT_ESCOLARIDADE;
DROP SEQUENCE AUTO_INCREMENT_TIPO_USUARIO;

--CRIAÇÃO DE SEQUENCIAS PARA CRIAÇÃO AUTOMATICA DE IDS
CREATE SEQUENCE AUTO_INCREMENT_PRONTUARIO
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE;
  
CREATE SEQUENCE AUTO_INCREMENT_MEDICAMENTO
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE;
  
CREATE SEQUENCE AUTO_INCREMENT_CONSULTA
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE;
  
CREATE SEQUENCE AUTO_INCREMENT_RECEITA
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE;
  
CREATE SEQUENCE AUTO_INCREMENT_RECEITA_MEDICAMENTO
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE;
  
CREATE SEQUENCE AUTO_INCREMENT_AVALIACAO
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE;

CREATE SEQUENCE AUTO_INCREMENT_ESCOLARIDADE
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE;

CREATE SEQUENCE AUTO_INCREMENT_TIPO_USUARIO
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE;

--CRIAÇAO TA TABELA DE ESCOLARIDADE  
CREATE TABLE tb_escolaridade(
    id_escolaridade NUMBER(6) DEFAULT AUTO_INCREMENT_ESCOLARIDADE.NEXTVAL CONSTRAINT id_esc_pk PRIMARY KEY,
    escolaridade VARCHAR2(35) CONSTRAINT esc_esc_nn NOT NULL CONSTRAINT esc_esc_u UNIQUE
);

--CRIAÇAO DA TABELA DE USUARIOS
CREATE TABLE tb_tipo_usuario(
    id_tipo_usuario NUMBER(6) DEFAULT AUTO_INCREMENT_TIPO_USUARIO.NEXTVAL CONSTRAINT id_tpuser_pk PRIMARY KEY,
    tipo_usuario VARCHAR2(10) CONSTRAINT tpuser_tpuser_nn NOT NULL CONSTRAINT tpuser_tpuser_u UNIQUE
);

--CRIAÇÃO DA PATTERN DE USUARIOS
CREATE TABLE main_usuario(
    cpf NUMBER(11) CONSTRAINT cpf_user_pk PRIMARY KEY,
    nome VARCHAR2(60) CONSTRAINT nm_user_nn NOT NULL,
    genero CHAR(1) CONSTRAINT genero_user_nn NOT NULL,
    num_telefone NUMBER(11) CONSTRAINT tel_user_nn NOT NULL,
    id_escolaridade NUMBER(6) CONSTRAINT escol_user_fk REFERENCES tb_escolaridade,
    dt_nasc DATE CONSTRAINT nasc_user_nn NOT NULL,
    id_tipo_usuario NUMBER(6) CONSTRAINT tp_user_fk REFERENCES tb_tipo_usuario,
    email VARCHAR2(80) CONSTRAINT email_user_nn NOT NULL,
    senha VARCHAR2(40) CONSTRAINT senha_user_nn NOT NULL,
    cep CHAR(8) CONSTRAINT cep_user_nn NOT NULL,
    logradouro VARCHAR2(60) CONSTRAINT log_user_nn NOT NULL,
    numero VARCHAR2(8) CONSTRAINT num_user_nn NOT NULL,
    bairro VARCHAR2(60) CONSTRAINT bairro_user_nn NOT NULL, 
    complemento VARCHAR2(60),
    cidade VARCHAR2(30) CONSTRAINT city_user_nn NOT NULL,
    estado CHAR(2) CONSTRAINT uf_user_nn NOT NULL
);

--CRIAÇÃO DA ESPECIALIZAÇÃO DE USUARIO PACIENTE
CREATE TABLE special_paciente(
    cpf NUMBER(11) CONSTRAINT cpf_pac_pk PRIMARY KEY,
    filhos NUMBER(2) CONSTRAINT filhos_pac_nn NOT NULL,
    ocupacao VARCHAR2(60) CONSTRAINT ocp_pac_nn NOT NULL,
    estado_civil VARCHAR2(20) CONSTRAINT est_civ_pac_nn NOT NULL,
    niss NUMBER(11) CONSTRAINT niss_pac_nn NOT NULL,
    FOREIGN KEY (cpf) REFERENCES main_usuario (cpf)
);

--CRIAÇÃO DA ESPECIALIZAÇÃO DE USUARIO PSIQUIATRA
CREATE TABLE special_profissional(
    cpf NUMBER(11) CONSTRAINT cpf_prof_pk PRIMARY KEY,
    certificacao NUMBER(7) CONSTRAINT crm_prof_nn NOT NULL CONSTRAINT crm_prof_u UNIQUE ,
    formacao VARCHAR2(35) CONSTRAINT form_prof_nn NOT NULL,
    cnpj NUMBER(11),
    FOREIGN KEY (cpf) REFERENCES main_usuario(cpf)
);



--CRIAÇÃO DA TABELA DE CONSULTAS
CREATE TABLE tb_consulta(
    id_consulta NUMBER(6) DEFAULT AUTO_INCREMENT_CONSULTA.NEXTVAL CONSTRAINT id_cons_pk PRIMARY KEY,
    cpf_paciente NUMBER(11) CONSTRAINT cpf_pac_cons_fk REFERENCES special_paciente,
    cpf_profissional NUMBER(11) CONSTRAINT cpf_prof_cons_fk REFERENCES special_profissional,
    data_hora DATE CONSTRAINT data_cons_nn NOT NULL,
    link_consulta VARCHAR2(400)
);

--CRIAÇÃO DA TABELA DE AVALIAÇÃO DAS CONSULTAS
CREATE TABLE tb_avaliacao(
    id_avaliacao NUMBER(6) DEFAULT AUTO_INCREMENT_AVALIACAO.NEXTVAL CONSTRAINT id_av_pk PRIMARY KEY,
    nota NUMBER(1) CONSTRAINT nota_av_nn NOT NULL,
    avaliacao VARCHAR2(350),
    id_consulta NUMBER(6) CONSTRAINT cons_av_fk REFERENCES tb_consulta
);

--CRIAÇÃO DA TABELA DE PRONTUARIO MEDICO
CREATE TABLE tb_prontuario(
    id_prontuario NUMBER(6) DEFAULT AUTO_INCREMENT_PRONTUARIO.NEXTVAL CONSTRAINT id_pron_pk PRIMARY KEY,
    id_consulta NUMBER(6) CONSTRAINT cons_pron_fk REFERENCES tb_consulta,
    data_hora DATE  CONSTRAINT data_pron_nn NOT NULL,
    descricao VARCHAR2(4000) CONSTRAINT desc_pron_nn NOT NULL
);

--CRIAÇÃO DA TABELA DE MEDICAMENTOS
CREATE TABLE tb_medicamento(
    id_medicamento NUMBER(6) DEFAULT AUTO_INCREMENT_MEDICAMENTO.NEXTVAL CONSTRAINT id_med_pk PRIMARY KEY,
    nome VARCHAR2(60) CONSTRAINT  nm_med_nn NOT NULL,
    fabricante VARCHAR2(45) CONSTRAINT  fab_med_nn NOT NULL, 
    via_admin VARCHAR2(30) CONSTRAINT  via_med_nn NOT NULL,
    principio_ativo VARCHAR2(40) CONSTRAINT  pa_med_nn NOT NULL
);

--CRIAÇÃO DA TABELA DE RECEITA MEDICA
CREATE TABLE tb_receita(
    id_receita NUMBER(6) DEFAULT AUTO_INCREMENT_RECEITA.NEXTVAL CONSTRAINT id_receita_pk PRIMARY KEY,
    data_hora DATE CONSTRAINT dt_receita_nn NOT NULL,
    id_consulta NUMBER(6) CONSTRAINT cons_receita_fk REFERENCES tb_consulta 
);

--CRIAÇÃO DA TABELA ASSOCIATIVA ENTRE A RECEITA E MEDICAMENTOS
CREATE TABLE assoc_receita_medicamento(
    id_receita_medicamento NUMBER(6) DEFAULT AUTO_INCREMENT_RECEITA_MEDICAMENTO.NEXTVAL CONSTRAINT id_receitaMedicamento_pk PRIMARY KEY,
    descricao VARCHAR2(150) CONSTRAINT desc_receitaMedicamento_nn NOT NULL,
    freq_admin VARCHAR2(40) CONSTRAINT freq_receitaMedicamento_nn NOT NULL,
    duracao_admin VARCHAR2(40) CONSTRAINT dur_receitaMedicamento_nn NOT NULL,
    id_receita NUMBER(6) CONSTRAINT receita_receitaMedicamento_fk REFERENCES tb_receita,
    id_medicamento NUMBER(6) CONSTRAINT medicamento_receitaMedicamento_fk REFERENCES tb_medicamento
);














